import "./globals.css";


export const metadata = {
  title: "TheTronicvaultt",
  description: "Generated by create next app",

  icons:{
    icon: "/favicon.png"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
